application: expensiveclock
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.gif
  static_files: img/favicon.gif
  upload: img/favicon.gif

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: .*
  script: python/main.py
